name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.5.6
        env:
          MYSQL_ROOT_PASSWORD: 'XX7hZA%R#S3DeC%43Z9q'
          MYSQL_DATABASE: 'dfcu'
          MYSQL_USER: 'root'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=1

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.3'
        
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

#     - name: Linting
#       run: ./vendor/bin/phpcs --ignore=Database/Migrations --ignore=Resources/Views
      
    - name: Generate key
      run: php artisan key:generate
    
    - name: Migrate database
      run: php artisan migrate --env=testing --force
      
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_PORT: 3306
        DB_DATABASE: dfcu
      run: vendor/bin/phpunit
	 
    # Continuous deployment
    # deploy:
    #   runs-on: ubuntu-latest
    #   needs: laravel
    #   # This will deploy your code to your server if it is merged into master.
    #   if: github.ref == 'refs/heads/main'
    #   steps:
    #     - name: Execute container
    #       run: docker exec -i dfcu_backend sh /var/www/html
